name: Test and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_DATABASE: hotelmanagement_test
          MYSQL_USER: mangsacoding
          MYSQL_PASSWORD: mangsacoding
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mysqli, pdo_mysql

    - name: Install Dependencies
      run: composer install

    - name: Wait for MySQL
      run: |
        while ! mysqladmin ping -h"127.0.0.1" -P"3306" --silent; do
          sleep 1
        done

    - name: Setup Database
      run: |
        mysql -h 127.0.0.1 -P 3306 -u mangsacoding -pmangsacoding < db/schema.sql

    - name: Run Tests
      run: ./vendor/bin/phpunit
      env:
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: hotelmanagement_test
        DB_USERNAME: mangsacoding
        DB_PASSWORD: mangsacoding

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd /path/to/your/project
          ./scripts/deploy.sh
